# Generated by Django 3.2.8 on 2023-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jim',
            field=models.EmailField(default='jim@jim.jim', max_length=254),
        ),
    ]
