# Generated by Django 3.2.8 on 2023-03-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_jim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jim',
        ),
    ]
